name: Build App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libgtk-4-dev build-essential
      - name: Build
        run: |
          cd samp-linux
          cmake -B cmake-build .
          cmake --build cmake-build/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-build-samp
          path: samp-linux/cmake-build/
